JY-102 : TableViewCell을 스와이프하여 삭제한다.
DONOTINTO/LottoNumberCreator pull request #10
Opened 2023-04-23 08:18 UTC by DONOTINTO

- 카드번호 : [JY-102](https://keentutoring.atlassian.net/browse/JY-102)
  - cell을 우→좌로 스와이프하면 해당 기록을 realm에서 삭제하고 해당 TableViewCell을 삭제한다.

2023-04-23 10:22 UTC, keenkim1202 requested changes

2023-04-23 10:22 UTC, keenkim1202 commented on LottoNumberCreator/LottoNumberCreator/ViewController.swift
> +                let lottoNumbers: String = {
고차함수 `.map()`와 string관련 메서드인 `.joined()` 를 활용해볼 수 있습니다.

```suggestion
                let lottoNumbers = data.map{ String($0) }.joined(separator: ".")
```

2023-04-23 10:22 UTC, keenkim1202 commented on LottoNumberCreator/LottoNumberCreator/ViewController.swift
> +        let action = UIContextualAction(style: .normal, title: "삭제") {_,_,completion in
```suggestion
        let action = UIContextualAction(style: .normal, title: "삭제") { _, _, completion in
```

2023-04-24 11:14 UTC, DONOTINTO commented on LottoNumberCreator/LottoNumberCreator/ViewController.swift
> +                let lottoNumbers: String = {
@keenkim1202 수정 완료했습니다!

2023-04-24 14:17 UTC, keenkim1202 approved these changes

2023-04-24 14:17 UTC, merged